//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techleb.WebApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public job()
        {
            this.bids_customer = new HashSet<bids_customer>();
            this.job_images = new HashSet<job_images>();
            this.notifications_tech = new HashSet<notifications_tech>();
        }
    
        public int job_id { get; set; }
        public int c_id { get; set; }
        public int phone_id { get; set; }
        public int location_id { get; set; }
        public string job_title { get; set; }
        public string profession_needed { get; set; }
        public string job_description { get; set; }
        public System.DateTime job_date { get; set; }
        public System.TimeSpan job_time { get; set; }
        public short job_is_deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bids_customer> bids_customer { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job_images> job_images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notifications_tech> notifications_tech { get; set; }
    }
}
