//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techleb.WebApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_images
    {
        public int image_id { get; set; }
        public int job_id { get; set; }
        public short image_is_deleted { get; set; }
        public string image_link { get; set; }
    
        public virtual job job { get; set; }
    }
}
