//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techleb.WebApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class messaging
    {
        public int msg_id { get; set; }
        public int sender { get; set; }
        public int receiver { get; set; }
        public short msg_is_deleted { get; set; }
        public short msg_is_starred { get; set; }
        public System.DateTime msg_date { get; set; }
        public System.TimeSpan msg_time { get; set; }
        public string msg_text { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
