//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techleb.WebApi.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class techlebEntities : DbContext
    {
        public techlebEntities()
            : base("name=techlebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bids_customer> bids_customer { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<job_images> job_images { get; set; }
        public virtual DbSet<messaging> messagings { get; set; }
        public virtual DbSet<notifications_tech> notifications_tech { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_feedback> user_feedback { get; set; }
        public virtual DbSet<user_images> user_images { get; set; }
        public virtual DbSet<user_locations> user_locations { get; set; }
        public virtual DbSet<user_phone_numbers> user_phone_numbers { get; set; }
        public virtual DbSet<user_professions> user_professions { get; set; }
    }
}
