//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techleb.WebApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_professions
    {
        public int profession_id { get; set; }
        public int u_id { get; set; }
        public short profession_is_deleted { get; set; }
        public string profession { get; set; }
        public short profession_is_displayed { get; set; }
    
        public virtual user user { get; set; }
    }
}
