//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techleb.WebApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_feedback
    {
        public int feedback_id { get; set; }
        public int c_id { get; set; }
        public int t_id { get; set; }
        public int feedback_text { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
